select NAME_BABY, sum(BABY_COUNT)
from NAMES_POPULARITY
inner join NAMES1 using(name_id) 
GROUP BY NAME_BABY;

select NAME_BABY,(SUM(BABY_COUNT)*100)/(select SUM(BABY_COUNT) from NAMES_POPULARITY)
from NAMES_POPULARITY
inner join NAMES1 using(name_id) 
GROUP BY NAME_BABY;

select BD_YEAR, SUM(BABY_COUNT)
from NAMES_POPULARITY
GROUP BY BD_YEAR;

